### ISSUE TITLE
Roadmap for the theme

### ISSUE THREAD

**Issue by hsoj95** [hsoj95/Gab.ai-Dark-Theme-2.0#1]
Here is the general roadmap for the theme:
*Note, this is just a general overview. In depth work will be needed for each part, starting most importantly with the first point on here

- [ ] Remove/fix parts of the code that completely break the webpage (Very Important!)

- [ ] Update remaining code to function properly with Gab's newest design styles (Important)

- [ ] Add features to spice up the theme and improve functionality (Less Important)

- [ ] Keep style up to date with Gab's ever changing styles and features (On-Going)
